// frontend/src/app/form/form.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-form',
  imports: [],
  templateUrl: './form.component.html',
  styleUrl: './form.component.scss'
})
export class FormComponent {

  getConection() {
    console.log('getConection');
  }
}

<form [action]="getConection()" method="post">
    <div class="mb-3">
        <label for="name">Nome de usuário</label>
        <input type="text" class="form-control" id="name" placeholder="Digite seu nome de usuário" />
    </div>
    <div class="mb-3">
        <label for="interest">Area de interesse</label>
        <select class="form-select" name="interest" id="interest">
            <option selected>Selecione uma opção</option>
            <option value="1">Sistema de reconhecimento facial</option>
            <option value="2">Matchmaking inteligente com propósito</option>
            <option value="3">
                Ferramenta de recrutamento com IA preditiva e alinhamento cultural
            </option>
            <option value="4">
                Ecossistema digital para o setor de eventos e inovação
            </option>
        </select>
    </div>
    <div class="mb-3">
        <label for="location">Localização</label>
        <select class="form-select" name="location" id="location">
            <option selected>Selecione uma opção</option>
            <option :value="01">Acre</option>
            <option :value="02">Alagoas</option>
            <option :value="03">Amazonas</option>
            <option :value="04">Amapá</option>
            <option :value="05">Bahia</option>
            <option :value="06">Ceará</option>
            <option :value="07">Espírito Santo</option>
            <option :value="08">Goiás</option>
            <option :value="09">Maranhão</option>
            <option :value="10">Minas Gerais</option>
            <option :value="11">Mato Grosso do Sul</option>
            <option :value="12">Mato Grosso</option>
            <option :value="13">Pará</option>
            <option :value="14">Paraíba</option>
            <option :value="15">Pernambuco</option>
            <option :value="16">Piauí</option>
            <option :value="17">Paraná</option>
            <option :value="18">Rio de Janeiro</option>
            <option :value="19">Rio Grande do Norte</option>
            <option :value="20">Rondônia</option>
            <option :value="21">Roraima</option>
            <option :value="22">Rio Grande do Sul</option>
            <option :value="23">Santa Catarina</option>
            <option :value="24">Sergipe</option>
            <option :value="25">São Paulo</option>
            <option :value="26">Tocantins</option>
        </select>
    </div>
    <input type="submit" value="Buscar Conexão" class="btn btn-primary" />
</form>

// frontend/src/components/FormComponent.vue
<script setup>

</script>

<template>
    <form action="">
        <div class="mb-3">
            <label class="form-label" for="name">Digite seu nome:</label>
            <input class="form-control" v-model="name" type="text" id="name" name="name" placeholder="Digite seu nome">
        </div>
        <div class="mb-3">
            <label class="form-label" for="interest-area">Selecione uma área de interesse</label>
            <select class="form-select" v-model="interest_area" name="interest-area" id="interest-area">
                <optgroup>
                    <option :value="0">--SELECIONE UMA ÁREA DE INTERESSE--</option>
                </optgroup>
                <optgroup>
                    <option :value="1">Credenciamento seguro</option>
                    <option :value="2">Fazer conexões inteligentes</option>
                    <option :value="3">Recrutamente com IA para alinhamento cultural</option>
                    <option :value="4">Ecossistema digital para eventos</option>
                </optgroup>
            </select>
        </div>
        <div class="mb-3">
            <label class="form-label" for="location">Selecione um estado</label>
            <select class="form-select" v-model="location" name="location" id="location">
                <optgroup>
                    <option :value="0">--SELECIONE UM ESTADO--</option>
                </optgroup>
                <optgroup>
                    <option :value="01">São Paulo</option>
                    <option :value="02">Rio de Janeiro</option>
                    <option :value="03">Minas Gerais</option>
                    <option :value="04">Espírito Santo</option>
                    <option :value="05">Bahia</option>
                    <option :value="06">Rio Grande do Sul</option>
                    <option :value="07">Paraná</option>
                    <option :value="08">Santa Catarina</option>
                    <option :value="09">Goiás</option>
                    <option :value="10">Mato Grosso</option>
                    <option :value="11">Mato Grosso do Sul</option>
                    <option :value="12">Tocantins</option>
                    <option :value="13">Pará</option>
                    <option :value="14">Amazonas</option>
                    <option :value="15">Roraima</option>
                    <option :value="16">Amapá</option>
                    <option :value="17">Acre</option>
                    <option :value="18">Rondônia</option>
                    <option :value="19">Maranhão</option>
                    <option :value="20">Piauí</option>
                    <option :value="21">Ceará</option>
                    <option :value="22">Rio Grande do Norte</option>
                    <option :value="23">Pernambuco</option>
                    <option :value="24">Paraíba</option>
                    <option :value="25">Alagoas</option>
                    <option :value="26">Sergipe</option>
                </optgroup>
            </select>
        </div>
        <input class="btn btn-primary mb-3" type="submit" value="Buscar Conexões">
    </form>
</template>

<style>
    
</style>
