// frontend/src/app/form/form.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-form',
  imports: [],
  templateUrl: './form.component.html',
  styleUrl: './form.component.scss'
})
export class FormComponent {

  getConection() {
    console.log('getConection');
  }
}

<form [action]="getConection()" method="post">
    <div class="mb-3">
        <label for="name">Nome de usuário</label>
        <input type="text" class="form-control" id="name" placeholder="Digite seu nome de usuário" />
    </div>
    <div class="mb-3">
        <label for="interest">Area de interesse</label>
        <select class="form-select" name="interest" id="interest">
            <option selected>Selecione uma opção</option>
            <option value="1">Sistema de reconhecimento facial</option>
            <option value="2">Matchmaking inteligente com propósito</option>
            <option value="3">
                Ferramenta de recrutamento com IA preditiva e alinhamento cultural
            </option>
            <option value="4">
                Ecossistema digital para o setor de eventos e inovação
            </option>
        </select>
    </div>
    <div class="mb-3">
        <label for="location">Localização</label>
        <select class="form-select" name="location" id="location">
            <option selected>Selecione uma opção</option>
            <option :value="01">Acre</option>
            <option :value="02">Alagoas</option>
            <option :value="03">Amazonas</option>
            <option :value="04">Amapá</option>
            <option :value="05">Bahia</option>
            <option :value="06">Ceará</option>
            <option :value="07">Espírito Santo</option>
            <option :value="08">Goiás</option>
            <option :value="09">Maranhão</option>
            <option :value="10">Minas Gerais</option>
            <option :value="11">Mato Grosso do Sul</option>
            <option :value="12">Mato Grosso</option>
            <option :value="13">Pará</option>
            <option :value="14">Paraíba</option>
            <option :value="15">Pernambuco</option>
            <option :value="16">Piauí</option>
            <option :value="17">Paraná</option>
            <option :value="18">Rio de Janeiro</option>
            <option :value="19">Rio Grande do Norte</option>
            <option :value="20">Rondônia</option>
            <option :value="21">Roraima</option>
            <option :value="22">Rio Grande do Sul</option>
            <option :value="23">Santa Catarina</option>
            <option :value="24">Sergipe</option>
            <option :value="25">São Paulo</option>
            <option :value="26">Tocantins</option>
        </select>
    </div>
    <input type="submit" value="Buscar Conexão" class="btn btn-primary" />
</form>

// src/components/FormComponent.vue
<script setup>

</script>

<template>
  <form action="">
    <label for="name">Nome</label>
    <input v-model="name" type="text" id="name" name="name" placeholder="Digite seu nome">
    <label for="interest-area">Área de interesse</label>
    <select v-model="selected" name="interest-area" id="interest-area">
      <option :value="face_pass">Credenciamento seguro</option>
      <option :value="link_ai">Fazer conexões inteligentes</option>
      <option :value="fit_score">Recrutamente com IA para alinhamento cultural</option>
      <option :value="hub_x">Ecossistema digital para eventos</option>  
    </select>
    <label for="location">Estado</label>
    <select v-model="selected" name="location" id="location">
        <option :value="sp">São Paulo</option>
        <option :value="rj">Rio de Janeiro</option>
        <option :value="mg">Minas Gerais</option>
        <option :value="es">Espírito Santo</option>
        <option :value="ba">Bahia</option>
        <option :value="rs">Rio Grande do Sul</option>
        <option :value="pr">Paraná</option>
        <option :value="sc">Santa Catarina</option>
        <option :value="go">Goiás</option>
        <option :value="mt">Mato Grosso</option>
        <option :value="ms">Mato Grosso do Sul</option>
        <option :value="to">Tocantins</option>
        <option :value="pa">Pará</option>
        <option :value="am">Amazonas</option>
        <option :value="rr">Roraima</option>
        <option :value="ap">Amapá</option>
        <option :value="ac">Acre</option>
        <option :value="ro">Rondônia</option>
        <option :value="ma">Maranhão</option>
        <option :value="pi">Piauí</option>
        <option :value="ce">Ceará</option>
        <option :value="rn">Rio Grande do Norte</option>
        <option :value="pe">Pernambuco</option>
        <option :value="pb">Paraíba</option>
        <option :value="al">Alagoas</option>
        <option :value="se">Sergipe</option>
    </select>
    <input type="submit" value="Buscar Conexões">
  </form>
</template>

<style>

</style>
